theme: jekyll-theme-cayman
title: Security Methodology
description: Tools, templates, guides, papers, scripts, research and ad hoc project services.
google_analytics: G-8DFDTW0NV
repository: isiahjonesSTEM/security-methodology
baseurl: /security-methodology
url: https://isiahjonesstem.github.io
include:
  - photos
keep_files:
  - photos  
exclude:
  - Security_Research/DeepHunter_https___pentest-ground.com_20260417_163618